version: "3.8"
services:
  web:
    image: traefik/whoami
    ports:
      - "8080:80"
    networks:
      - lores
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        traefik.enable: "true"
        traefik.http.routers.web.rule: "Host(`example.lores.localhost`)"
        traefik.http.routers.web.entryPoints: web
        traefik.http.routers.web.service: web
        traefik.http.services.web.loadbalancer.server.port: 80
volumes:
  config:
networks:
  lores:
    external: true
